DubiStor/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Business;
using Business.IBusiness;
using DomainModel;
using DubiStor.infrastructure;
using DubiStor.Models;
using DubiStor.UserHelper;

namespace DubiStor.Controllers
{
    public class UserLoginController : Controller
    {
        public IPublicUserBusiness _publicuerbus;
        public ITemplateBusiness _templatebus;
        public TemplateDomainModel templatedm;
        public PublicUserDomainModel publicuserdm;
        public ICommonSettingBusiness _commonsettingbus;
        public Message msg;
        public UserLoginController()
        {
            _publicuerbus = new PublicUserBusiness();
            _templatebus = new TemplateBusiness();
            _commonsettingbus = new CommonSettingBusiness();
            publicuserdm = new PublicUserDomainModel();
            templatedm = new TemplateDomainModel();
            msg = new Message();
        }
        // GET: UserLogin
        public ActionResult Index()
        {
            return View();
        }
        #region Login
        public ActionResult Login()
        {
            return View();
        }
        #endregion

        [HttpPost]
        public ActionResult Login(PublicUserViewModel publicuservm)
        {
            publicuserdm=_publicuerbus.Get(publicuservm.Email);
            if (publicuserdm != null) {
                if (publicuserdm.Email == publicuservm.Email && publicuserdm.Password == publicuservm.Password) {
                    TempData["msg"] = "welcome";
                    CurrentPublicUser User = new CurrentPublicUser();
                    User.PubUserID = publicuserdm.PubUserID;
                    User.FirstName = publicuserdm.FirstName;
                    User.LastName = publicuserdm.LastName;
                    User.Email = publicuserdm.Email;
                    //  CurrentPublicSession._HttpContextAccessor("CurrentPublicUser", User);
                 //   Session["CurrentPublicUser"] = User;
                    CurrentPublicSession.PublicUser = User;
                    return RedirectToAction("Index", "Dashboard", new { area = "User" });
                }
                else {
                    TempData["Msg"] = "Username or Password is not correct";
                    return View(publicuservm);

                }
            }
            else {
                TempData["Msg"] = "Username not exist";
                return View(publicuservm);
            }
        }

        #region Register
        public ActionResult Register()
        {
            return View();
        }
        #endregion

        public ActionResult Privacy()
        {
            // Create a random state
            string state = Guid.NewGuid().ToString();
            // Create the url
            string url = "https://www.facebook.com/dialog/oauth?client_id=" + "228721164991378" + "&state=" +
            state + "&response_type=code&redirect_uri=" + "https://localhost:44355" + "/home/callback";
            // Redirect the user
            return Redirect(url);
        }
        #region Email body Html In profile create        
        private string PopulateEmailBody(PublicUserDomainModel result, string emailBody)
        {
            var siteUrl = _commonsettingbus.Get("smtp.zoho.com").SiteURL;
            emailBody = emailBody.Replace("#FirstName#", Convert.ToString(result.FirstName));
            emailBody = emailBody.Replace("#LastName#", Convert.ToString(result.LastName));
            emailBody = emailBody.Replace("#click here#", "<a href=" + string.Format(siteUrl) + "UserLogin/Verified?EmailID=" + GlobalCode.UrlEncrypt(result.Email) + ">click here</a>");

            return emailBody;
        }
        #endregion
        [HttpPost]
        public ActionResult Register(PublicUserViewModel publicuservm)
        {
            if (publicuservm.Password == publicuservm.ConfirmPassword) {
                publicuserdm = _publicuerbus.Get(publicuservm.Email);
                if (publicuserdm == null) {

                    publicuservm.IsEmailVerfied = false;
                    publicuservm.IsSocialLogin = false;
                    publicuservm.ProfilePicture = "";
                    publicuservm.Status = true;
                    publicuservm.DateJoined = DateTime.Now;
                    PublicUserDomainModel publicuserdmobj = new PublicUserDomainModel();
                    AutoMapper.Mapper.Map(publicuservm, publicuserdmobj);
                    msg = _publicuerbus.Add(publicuserdmobj);
                    if (msg.Result == true) {
                        templatedm=_templatebus.Get("Account Verification");
                        string emailBody = templatedm.Body;
                        emailBody = PopulateEmailBody(publicuserdmobj, emailBody);
                        SendModuleEmail(publicuserdmobj.Email, templatedm.Subject, emailBody);
                        TempData["Msg"] = "Email has been Sent on your mail address Kindly Verify it.";
                        return RedirectToAction("Message", "Home");
                        //return View(publicuservm);
                    }
                    else {
                        TempData["Msg"] = "Error Performing this Operation";
                        return View(publicuservm);
                    }

                }
                else {
                    TempData["Msg"] = "This Username already Exist";
                    return View(publicuservm);
                }
            }
            else {
                TempData["Msg"] = "Password Mismatch";
                return View(publicuservm);
            }
        }

        #region Send Email Module
        public bool SendModuleEmail(string recipients, string subject, string emailBody, string CC = "")
        {
            SmtpClient _SmtpClient = new SmtpClient();
            MailMessage _msgCsutomer = new MailMessage();
            bool isSend = false;
            var Commonsetting = _commonsettingbus.Get("smtp.zoho.com");
            string strFrom = Convert.ToString(Commonsetting.Email);
            _msgCsutomer.From = new MailAddress(strFrom);
            var arrrecipients = recipients.Split(',').ToList();
            foreach (var recipient in arrrecipients) {
                _msgCsutomer.To.Add(recipient);
            }

            if (!string.IsNullOrEmpty(CC)) {
                var arrCC = CC.Split(',').ToList();
                foreach (var cc in arrCC) {
                    _msgCsutomer.CC.Add(cc);
                }
            }
            _msgCsutomer.Subject = subject;
            _msgCsutomer.IsBodyHtml = true;
            _msgCsutomer.Body = emailBody;
            _SmtpClient.Host = Convert.ToString(Commonsetting.SMTPServer);
            _SmtpClient.Port = Convert.ToInt32(Commonsetting.Port);
            _SmtpClient.Credentials = new NetworkCredential(Commonsetting.Email, Commonsetting.Password);
            _SmtpClient.EnableSsl = Convert.ToBoolean(Commonsetting.IsSSL);
            _SmtpClient.Send(_msgCsutomer);
            isSend = true;
            return isSend;
        }
        #endregion
        public ActionResult Google()
        {
            //     var Googleurl = "https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=" + googleplus_redirect_url + "&scope=https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&client_id=" + googleplus_client_id;

            //https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?response_type=code&client_id=505669636385-0ad3rmofgmhielkbknqim5k1s8d29a4d.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fauth.web.dev%2F__%2Fauth%2Fhandler&state=AMbdmDmKMJkyVEdZq33YB-UFktf-6xWTOC6gOqEJsx_kovXdqZztvjUf54WlJYb9HrspLze5PFyOYCQeiIUQkQwCdXlQ9GVl9GlKme-XRGj9lLXK72cQNtf56A6-S1zKvlrAgXDfvAQNweJLwm7PY_U29RViM3eYd0NNJYfof66RHsBtq9bMChzcThpP0-PibTkxPNqojHM7E0DuVfahyZxgyK2Z-1yTieKrIrqwOr8jgOqEX8W2NQci-H_tSha0AvXme47MvWCNTMqcHTTQTxsbmOoCmq3X2mStblTEaeF4XebnXcxE&scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20profile&context_uri=https%3A%2F%2Fweb.dev&flowName=GeneralOAuthFlow
            // Create a random state
            string state = Guid.NewGuid().ToString();
            string url = "https://accounts.google.com/o/oauth2/v2/auth?" +
            "scope=openid email profile&" +
                //"include_granted_scopes=true&" +
                "response_type=code&" +
                "state=" + state + "&" +
                "redirect_uri=https://localhost:44322" + "/UserLogin/callbackg&" +
                "client_id=505669636385-0ad3rmofgmhielkbknqim5k1s8d29a4d.apps.googleusercontent.com";
            return Redirect(url);
        }

        public ActionResult FaceBook()
        {
            string state = Guid.NewGuid().ToString();
            var url = "https://www.facebook.com/v8.0/dialog/oauth?" +
                "response_type=code&" +
                "display=popup&" +
                "state=" + state + "&" +
                "redirect_uri=https://localhost:44322" + "/UserLogin/callback&" +
                "client_id=1605867736260802";
            //var facebookurl = "https://www.facebook.com/v8.0/dialog/oauth?&client_id=1605867736260802&display=popup&domain=https://localhost:44322/UserLogin/callback&e2e=%7B%7D&redirect_uri=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df3f109e2989fe0c%26domain%3Dlocalhost%26origin%3Dhttps%253A%252F%252Flocalhost%253A44322%252Ff1d1ca646c0d6c8%26relation%3Dopener.parent%26frame%3Df285d937f7b8e8&scope=public_profile%2Cemail&sdk=joey&url=https://localhost:44322/UserLogin/callback&version=v8.0";
            return Redirect(url);
        }
        #region forget password
        public ActionResult ForgetPassword()
        {
            return View();
        }
        #endregion
        public ActionResult Verified(string EmailID)

DubiStor/Areas/User/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}


<head>
    @Styles.Render("~/Css")
    <link href="https://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href=" https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style type="text/css">

        .customer-photo {
            display: inline-block;
            width: 35px;
            height: 35px;
            border-radius: 50%;
            background-size: 32px 35px;
            background-position: center center;
            vertical-align: middle;
            line-height: 32px;
            box-shadow: inset 0 0 1px #999, inset 0 0 10px rgba(0,0,0,.2);
            margin-left: 43px;
        }

        /* The switch - the box around the slider */
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
            float: right;
        }

            /* Hide default HTML checkbox */
            .switch input {
                display: none;
            }

        /* The slider */
        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ff1414;
            -webkit-transition: .4s;
            transition: .4s;
        }

            .slider:before {
                position: absolute;
                content: "";
                height: 26px;
                width: 26px;
                left: 4px;
                bottom: 4px;
                background-color: white;
                -webkit-transition: .4s;
                transition: .4s;
            }

        input.default:checked + .slider {
            background-color: #0dcc62;
        }

        input.primary:checked + .slider {
            background-color: #2196F3;
        }

        input.success:checked + .slider {
            background-color: #8bc34a;
        }

        input.info:checked + .slider {
            background-color: #3de0f5;
        }

        input.warning:checked + .slider {
            background-color: #FFC107;
        }

        input.danger:checked + .slider {
            background-color: #f44336;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

            .slider.round:before {
                border-radius: 50%;
            }
    </style>
</head>
<header class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand logo_h" href="@Url.Action("Index","Home")"><img src="~/Content/web-assets/images/station/nota.jpg" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item active"><a href="@Url.Action("Index","Home")" onclick="showProgress()" class="nav-link">Home</a></li>
                        <li class="nav-item active"><a href="@Url.Action("Register","UserLogin")" onclick="showProgress()" class="nav-link">Register</a></li>
                        <li class="nav-item active"><a href="@Url.Action("Login","UserLogin")" onclick="showProgress()" class="nav-link">Login</a></li>

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>


@RenderBody()



<footer class="footer">
    <div class="footer-area">
        <div class="container">
            <div class="row section_gap">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title large_title">Our Mission</h4>
                        <p>
                            So seed seed green that winged cattle in. Gathering thing made fly you're no
                            divided deep moved us lan Gathering thing us land years living.
                        </p>
                        <p>
                            So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved
                        </p>
                    </div>
                </div>
                <div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title">Quick Links</h4>
                        <ul class="list">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Shop</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Product</a></li>
                            <li><a href="#">Brand</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget instafeed">
                        <h4 class="footer_title">Gallery</h4>
                        <ul class="list instafeed d-flex flex-wrap">
                            <li><img src="~/aroma/img/gallery/r1.jpg" alt=""></li>
                            <li><img src="~/aroma/img/gallery/r2.jpg" alt=""></li>
                            <li><img src="~/aroma/img/gallery/r3.jpg" alt=""></li>
                            <li><img src="~/aroma/img/gallery/r5.jpg" alt=""></li>
                            <li><img src="~/aroma/img/gallery/r7.jpg" alt=""></li>
                            <li><img src="~/aroma/img/gallery/r8.jpg" alt=""></li>
                        </ul>
                    </div>
                </div>
                <div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget tp_widgets">
                        <h4 class="footer_title">Contact Us</h4>
                        <div class="ml-40">
                            <p class="sm-head">
                                <span class="fa fa-location-arrow"></span>
                                Head Office
                            </p>
                            <p>123, Main Street, Your City</p>

                            <p class="sm-head">
                                <span class="fa fa-phone"></span>
                                Phone Number
                            </p>
                            <p>
                                +123 456 7890 <br>
                                +123 456 7890
                            </p>

                            <p class="sm-head">
                                <span class="fa fa-envelope"></span>
                                Email
                            </p>
                            <p>
                                free@infoexample.com <br>
                                www.infoexample.com
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row d-flex">
                <p class="col-lg-12 footer-text text-center">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>







@Scripts.Render("~/Js")

@RenderSection("scripts", required: false)
<script src="https://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js"></script>