DubiStor/Models/Preference.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DubiStor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int PreferenceID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}

DubiStor/Models/PreferenceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DubiStor.Models
{
    public class PreferenceViewModel
    {
        public int PreferenceID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}

DubiStor/Areas/Admin/Controllers/PreferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using Business.IBusiness;
using DomainModel;
using DubiStor.Models;

namespace DubiStor.Areas.Admin.Controllers
{
    public class PreferenceController : Controller
    {
        // GET: Admin/Preference
        public IPreferencesBusiness preferencebus;
        public List<PreferencesDomainModel> preferencedm;
        public Message msg;
        public PreferenceController() {
            preferencebus = new PreferencesBusiness();
            preferencedm = new List<PreferencesDomainModel>();
            msg = new Message();
        }
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetAll() {

            preferencedm=preferencebus.GetAll();
            return Json(new { data = preferencedm }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult AddUpdate(PreferenceViewModel preferencevm)
        {
            PreferencesDomainModel preferencedm = new PreferencesDomainModel();
            AutoMapper.Mapper.Map(preferencevm, preferencedm);
            if (preferencedm.PreferenceID > 0) {
                msg = preferencebus.Edit(preferencedm);
            }
            else {
                msg = preferencebus.Add(preferencedm);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public string Delete(int id)
        {
            msg = preferencebus.Delete(id);
            return msg.Response;
        }
    }
}

DubiStor/Areas/Admin/Views/Preference/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row ">
        <div class="col-12">
            <h1 class="text-center">Manager Preferences</h1>
        </div>
    </div>
</div>
<div class="card m-b-30">
    <div class="card-body">
        <form id="EventForm" action=@Url.Action("AddUpdate","Preference") method="post">
            <input type="hidden" id="PreferenceID" name="PreferenceID" class="form-control" placeholder="Event Id">

            <div class="form-group">
                <input type="text" id="Name" name="Name" class="form-control" placeholder="Preference Name">
            </div>
            <div class="form-group">
                <input type="text" id="Description" name="Description" class="form-control" placeholder="Preference Description">
            </div>
            <div class="form-group">
                <input type="checkbox" id="isActive" name="isActive" class="form-control" >
            </div>
            <div class="form-group">
                <input type="submit" id="prefsubmit" value="Add" class="btn bg-primary">
                <input type="button" id="cancelsubmit" value="Cancel" class="btn bg-light">
                <input type="button" id="deletebtn" value="Delete" class="btn bg-danger">
            </div>
        </form>

        <div>
            <h2 class="h4 mb-4">View Preference</h2>
            <table id="EventTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Active</th>
                    </tr>
                </thead>


            </table>
        </div><br />
        <div class="col-sm-12">

            <div class="row">
                <div class="">
                    <button type="submit" class="btn btn-secondary" title="Delete" onclick="return Check_CheckBox_Count('EventsID');"><i class="fa fa-trash"></i> Delete</button>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="row">
</div>

@section scripts{

    <script>
        $(document).ready(function () {
           // $("#PreferenceID").prop("disabled", true);
            $("#deletebtn").prop( "hidden", true );
            $("#Name").val("");
            $("#Description").val("");
            $("#isActive").prop('checked', false);
});
        $(function () {




            $('#EventForm').submit(function (e, params) {
        var localParams = params || {};
              //  alert (JSON.stringify(params));
        if (!localParams.send) {
            e.preventDefault();
        }

           //additional input validations can be done hear

    swal({
                title: "Confirm Entry",
                text: "Are you sure all entries are correct",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#6A9944",
                confirmButtonText: "Confirm",
                cancelButtonText: "Cancel",
                closeOnConfirm: true
            }, function (isConfirm) {
                if (isConfirm) {
                    $(e.currentTarget).trigger(e.type, { 'send': true });
                } else {

              //additional run on cancel  functions can be done hear

            }
        });
});

             $("#cancelsubmit").click(function(){
                 $("#prefsubmit").val("Add");
                 $("#PreferenceID").val("0");
                 $("#Name").val("");
                 $("#Description").val("");
                 $("#isActive").prop('checked', false);
                 $("#deletebtn").prop( "hidden", true );

             });
             $('#deletebtn').on('click', function (e, data) {
                handleDelete(e, 1);

                 // alert($("#EventID").val());

        });
           $("#EventTable").DataTable({

               "dom": '<"ButtonStuff"B><"FilterStuff"f>t',
    "ajax": {
    "url": '@Url.Action("GetAll", "Preference")',
    "type": "Get",
    "datatype": "json"
               },
               "columnDefs": [
                
                   {
                       "targets": [1],
                       "visible": false
                   }
               ],
    "columns": [
        {
            render: function (data, type, row) {//data
                return '<Button href="#" class="btn bg-secondary text-white" data-id="Id" onclick="EditPreference(' + row.PreferenceID + ',' + "'" + row.Name + "'" + ',' + "'" + row.Description + "'" + ',' + "'" + row.isActive + "'" +')">Select</Button> ';
            }
        },
        { "data": "PreferenceID", "name": "PreferenceID", "autoWidth": true },
        { "data": "Name", "name": "Name", "autoWidth": true }, 
        { "data": "Description", "name": "Description", "autoWidth": true },
        {
            render: function (data, type, row) {//data
                if (row.isActive == true) {
                    return '<label class="text-success" >Active</label> ';

                }
                else {
                    return '<label class="text-danger" >Not Active</label> ';
                }
                }
        }
    ]

    });

        });
        function EditPreference(ID, Name, description, active) {
         //   alert(ID);
            $( "#Name" ).focus();
            $("#PreferenceID").val(ID);
            $("#Name").val(Name); 
            $("#Description").val(description);
            if (active == "true") {
                $("#isActive").prop('checked', true);
            }
            else {
                $("#isActive").prop('checked', false);
            }

            $("#prefsubmit").val("Update");
            $("#deletebtn").prop( "hidden", false );
         }
        function handleDelete(e, stop) {
        if (stop) {
            e.preventDefault();
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover the deleted Event!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete!",
                closeOnConfirm: false
            },
            function (isConfirm) {
                if (isConfirm) {
                    swal("Deleted", "", "success");
                    $.get('@Url.Action("Delete","Preference")', { id: $("#PreferenceID").val() }, function (data) {
              //alert("deleting1");
              window.location = '@Url.Action("Index", "Preference")'});

                }
            });
        }
    };

    </script>
}