DubiStor/Areas/Admin/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using Business.IBusiness;
using DomainModel;
using DubiStor.Models;

namespace DubiStor.Areas.Admin.Controllers
{
    public class MembersController : Controller
    {
        // GET: Admin/Members
        public IPublicUserBusiness publicuserbus;
        public List<PublicUserDomainModel> publicuserlistdm;
        public Message msg;
        public MembersController() {
            publicuserbus = new PublicUserBusiness();
            publicuserlistdm = new List<PublicUserDomainModel>();
            msg = new Message();
        }
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetAll()
        {

            publicuserlistdm = publicuserbus.GetAll();
            return Json(new { data = publicuserlistdm }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult AddUpdate(PublicUserViewModel publicuservm)
        {
            PublicUserDomainModel publicuserdm = new PublicUserDomainModel();
            AutoMapper.Mapper.Map(publicuservm, publicuserdm);
            if (publicuserdm.PubUserID > 0) {
                msg = publicuserbus.Edit(publicuserdm);
            }
            else {
                msg = publicuserbus.Add(publicuserdm);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public string Delete(int id)
        {
            msg = publicuserbus.Delete(id);
            return msg.Response;
        }
    }
}

DubiStor/Areas/Admin/Views/Members/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="row ">
        <div class="col-12">
      <h1 class="text-center">Manager Members</h1>
            </div>
    </div>
</div>
<div class="card m-b-30">
    <div class="card-body">
        <form id="EventForm" action=@Url.Action("AddUpdate","Members") method="post">
            <div class="row">
                <input type="hidden" id="PubUserID" name="PubUserID" class="form-control">
                <div class="col-6">
                    <div class="form-group">
                        <input type="text" id="FirstName" name="FirstName" class="form-control" placeholder="First Name">
                    </div>
                    <div class="form-group">
                        <input type="text" id="LastName" name="LastName" class="form-control" placeholder="Last Name">
                    </div>
                    <div class="form-group">
                        <input type="text" id="Phone" name="Phone" class="form-control" placeholder="Phone">
                    </div>
                    <div class="form-group">
                        <input type="text" id="Email" name="Email" class="form-control" placeholder="Email">
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <input type="text" id="Address" name="Address" class="form-control" placeholder="Address">
                    </div>
                    <div class="form-group">
                        <input type="text" id="Gender" name="Gender" class="form-control" placeholder="Gender">
                    </div>
                    <div class="form-group">
                        <input type="checkbox" id="Status" name="Status" class="form-control" placeholder="Status">
                    </div>
                </div>
            </div>
        

        

       

            <div class="form-group">
                <input type="submit" id="prefsubmit" value="Add" class="btn bg-primary">
                <input type="button" id="cancelsubmit" value="Cancel" class="btn bg-light">
                <input type="button" id="deletebtn" value="Delete" class="btn bg-danger">
            </div>
        </form>

        <div>
            <h2 class="h4 mb-4">View Preference</h2>
            <table id="EventTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Gender</th>
                        <th>Status</th>
                      
                    </tr>
                </thead>


            </table>
        </div><br />
        <div class="col-sm-12">

            <div class="row">
                <div class="">
                    <button type="submit" class="btn btn-secondary" title="Delete" onclick="return Check_CheckBox_Count('EventsID');"><i class="fa fa-trash"></i> Delete</button>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="row">
</div>

@section scripts{

    <script>
        $(document).ready(function () {
           // $("#PreferenceID").prop("disabled", true);
            $("#deletebtn").prop( "hidden", true );
            $("#PubUserID").val("0");
            $("#FirstName").val("");
            $("#LastName").val("");
            $("#Phone").val("");
            $("#Email").val("");
            $("#Address").val("");
            $("#Gender").val("");
            $("#Status").prop('checked', false);

});
        $(function () {




            $('#EventForm').submit(function (e, params) {
        var localParams = params || {};
              //  alert (JSON.stringify(params));
        if (!localParams.send) {
            e.preventDefault();
        }

           //additional input validations can be done hear

    swal({
                title: "Confirm Entry",
                text: "Are you sure all entries are correct",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#6A9944",
                confirmButtonText: "Confirm",
                cancelButtonText: "Cancel",
                closeOnConfirm: true
            }, function (isConfirm) {
                if (isConfirm) {
                    $(e.currentTarget).trigger(e.type, { 'send': true });
                } else {

              //additional run on cancel  functions can be done hear

            }
        });
});

             $("#cancelsubmit").click(function(){
                 $("#prefsubmit").val("Add");
               
                 $("#PubUserID").val("0");
                 $("#FirstName").val("");
                 $("#LastName").val("");
                 $("#Phone").val("");
                 $("#Email").val("");
                 $("#Address").val("");
                 $("#Gender").val("");
                 $("#Status").prop('checked', false);


             });
             $('#deletebtn').on('click', function (e, data) {
                handleDelete(e, 1);

                 // alert($("#EventID").val());

        });
           $("#EventTable").DataTable({

               "dom": '<"ButtonStuff"B><"FilterStuff"f>t',
    "ajax": {
    "url": '@Url.Action("GetAll", "Members")',
    "type": "Get",
    "datatype": "json"
               },
               "columnDefs": [

                   {
                       "targets": [1],
                       "visible": false
                   }
               ],
    "columns": [
        {
            render: function (data, type, row) {//data
                return '<Button href="#" class="btn bg-secondary text-white" data-id="Id" onclick="EditMember(' + row.PubUserID + ',' + "'" + row.FirstName + "'" + ',' + "'" + row.LastName + "'" + ',' + "'" + row.Phone + "'" + ',' + "'" + row.Email + "'" + ',' + "'" + row.Address + "'" + ',' + "'" + row.Gender + "'" + ',' + "'" + row.Status + "'"  +')">Select</Button> ';
            }
        },
        { "data": "PubUserID", "name": "PubUserID", "autoWidth": true },
        {
            render: function (data, type, row) {//data
                return ' <label class="text-black" >' + row.FirstName + " " + row.LastName + '</label>';
            }
        },
        { "data": "Phone", "name": "Phone", "autoWidth": true },
        { "data": "Email", "name": "Email", "autoWidth": true },
        { "data": "Address", "name": "Address", "autoWidth": true },
        { "data": "Gender", "name": "Gender", "autoWidth": true },
        {
            render: function (data, type, row) {//data
                if (row.Status == true) {
                    return '<label class="text-success" >Active</label> ';

                }
                else {
                    return '<label class="text-danger" >Not Active</label> ';
                }
                }
        }
    ]

    });

        });
        function EditMember(ID, firstName,lastname,phone, email,address,gender, active) {
         //   alert(ID);
            $( "#FirstName" ).focus();
            $("#PubUserID").val(ID);
            $("#FirstName").val(firstName);
            $("#LastName").val(lastname);
            $("#Phone").val(phone);
            $("#Email").val(email);
            $("#Address").val(address);
            $("#Gender").val(gender);
            if (active == "true") {
                $("#Status").prop('checked', true);
            }
            else {
                $("#Status").prop('checked', false);
            }

            $("#prefsubmit").val("Update");
            $("#deletebtn").prop( "hidden", false );
         }
        function handleDelete(e, stop) {
        if (stop) {
            e.preventDefault();
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover the deleted Event!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete!",
                closeOnConfirm: false
            },
            function (isConfirm) {
                if (isConfirm) {
                    swal("Deleted", "", "success");
                    $.get('@Url.Action("Delete","Members")', { id: $("#PubUserID").val() }, function (data) {
              //alert("deleting1");
              window.location = '@Url.Action("Index", "Members")'});

                }
            });
        }
    };

    </script>
}